################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/%.o EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/%.su EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/%.cyclo: ../EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/%.c EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../Core/Inc -I../FATFS/Target -I../FATFS/App -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/BSP" -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/Setup" -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/EdgeIntelligence/CMSIS-DSP/Include" -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/EdgeIntelligence/CMSIS-NN/Include" -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/TinySHM" -I"E:/DEV/MCU_NODE_STM32/ONGOING/FRONTIER/App" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-EdgeIntelligence-2f-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

clean-EdgeIntelligence-2f-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.cyclo
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo
	-$(RM) ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.su ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o ./EdgeIntelligence/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-EdgeIntelligence-2f-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

